#ifndef MAILZ_MAILDIR_SEND_H
#define MAILZ_MAILDIR_SEND_H
enum maildir_send_status {
	MAILDIR_SEND_OK,
	MAILDIR_SEND_USAGE,
	MAILDIR_SEND_WRITE,
	MAILDIR_SEND_SWRITE,
	MAILDIR_SEND_UNVEIL,
	MAILDIR_SEND_PLEDGE,
	MAILDIR_SEND_PIPE,
	MAILDIR_SEND_FORK,
	MAILDIR_SEND_DUP,
	MAILDIR_SEND_CLOSE,
	MAILDIR_SEND_EXEC,
	MAILDIR_SEND_FDOPEN,
	MAILDIR_SEND_PRINTF,
	MAILDIR_SEND_GETC,
	MAILDIR_SEND_WAITPID,
	MAILDIR_SEND_SENDMAIL,
	MAILDIR_SEND_PUTC,
	MAILDIR_SEND_READ,
	MAILDIR_SEND_SREAD,
};
#endif /* MAILZ_MAILDIR_SEND_H */
