#ifndef MAILZ_MAILDIR_READ_LETTER_H
#define MAILZ_MAILDIR_READ_LETTER_H
enum maildir_letter_read_status {
	MAILDIR_READ_LETTER_OK,
	MAILDIR_READ_LETTER_USAGE,
	MAILDIR_READ_LETTER_WRITE,
	MAILDIR_READ_LETTER_SWRITE,
	MAILDIR_READ_LETTER_FOPEN,
	MAILDIR_READ_LETTER_CLOSE,
	MAILDIR_READ_LETTER_PLEDGE,
	MAILDIR_READ_LETTER_MALLOC,
	MAILDIR_READ_LETTER_PRINTF,
	MAILDIR_READ_LETTER_UTF8,
	MAILDIR_READ_LETTER_ASCII,
	MAILDIR_READ_LETTER_SETLOCALE,
	MAILDIR_READ_LETTER_PIPE,
	MAILDIR_READ_LETTER_FORK,
	MAILDIR_READ_LETTER_DUP,
	MAILDIR_READ_LETTER_EXEC,
	MAILDIR_READ_LETTER_FDOPEN,
	MAILDIR_READ_LETTER_WAITPID,
	MAILDIR_READ_LETTER_READ,
	MAILDIR_READ_LETTER_SREAD,
	MAILDIR_READ_LETTER_SNPRINTF,
	MAILDIR_READ_LETTER_TOOLONG,
};
#endif /* MAILZ_MAILDIR_READ_LETTER_H */
