#ifndef MAILZ_MAILDIR_READ_LETTER_H
#define MAILZ_MAILDIR_READ_LETTER_H
enum {
	IMSG_MDR_IGNORE,
	IMSG_MDR_IGNOREALL,
	IMSG_MDR_LINEWRAP,
	IMSG_MDR_PIPEOK,
	IMSG_MDR_RETAIN,
	IMSG_MDR_REORDER,
};
#endif /* MAILZ_MAILDIR_READ_LETTER_H */
