#ifndef MAILZ_MAILDIR_SETUP_H
#define MAILZ_MAILDIR_SETUP_H

enum maildir_setup_status {
	MAILDIR_SETUP_OK,
	MAILDIR_SETUP_USAGE,
	MAILDIR_SETUP_UNVEIL,
	MAILDIR_SETUP_PLEDGE,
	MAILDIR_SETUP_OPENMAIN,
	MAILDIR_SETUP_OPENCUR,
	MAILDIR_SETUP_OPENNEW,
	MAILDIR_SETUP_FDOPENNEW,
	MAILDIR_SETUP_READDIR,
	MAILDIR_SETUP_SNPRINTF,
	MAILDIR_SETUP_TOOLONG,
	MAILDIR_SETUP_RENAME,
	MAILDIR_SETUP_CLOSE,
	MAILDIR_SETUP_WRITE,
	MAILDIR_SETUP_SWRITE,

	MAILDIR_SETUP_PIPE,
	MAILDIR_SETUP_FORK,
	MAILDIR_SETUP_DUP,
	MAILDIR_SETUP_EXEC,
	MAILDIR_SETUP_WAITPID,
	MAILDIR_SETUP_READ,
	MAILDIR_SETUP_SREAD,
};
#endif /* MAILZ_MAILDIR_SETUP_H */
