#ifndef MAILZ_MAILDIR_READ_H
#define MAILZ_MAILDIR_READ_H
enum maildir_read_status {
	MAILDIR_READ_OK,
	MAILDIR_READ_USAGE,
	MAILDIR_READ_OPENDIR,
	MAILDIR_READ_PLEDGE,
	MAILDIR_READ_CLOSEDIR,
	MAILDIR_READ_READDIR,
	MAILDIR_READ_WRITE,
	MAILDIR_READ_SWRITE,
	MAILDIR_READ_FOPEN,
	MAILDIR_READ_LETTER,
	MAILDIR_READ_FCLOSE,
	MAILDIR_READ_UNVEIL,
	MAILDIR_READ_PIPE,
	MAILDIR_READ_FORK,
	MAILDIR_READ_DUP,
	MAILDIR_READ_EXEC,
	MAILDIR_READ_WAITPID,
	MAILDIR_READ_READ,
	MAILDIR_READ_SREAD,
	MAILDIR_READ_CLOSE,
	MAILDIR_READ_SNPRINTF,
	MAILDIR_READ_TOOLONG,
};
#endif /* MAILZ_MAILDIR_READ_H */
