PROG = mailz
SRCS = cache.c commands.c date.c extract.c ibuf-util.c imsg-sync.c
SRCS += letter.c lex.l list.c maildir.c mailz.c mark.c parse.y
SRCS += print.c printable.c read-letter.c read-letters.c send.c
SRCS += setup.c
LDADD = -lutil
NOMAN = 1

BINDIR = bin

.include <bsd.prog.mk>
