PROG = mailz
SRCS = cache.c commands.c imsg-util.c leak.c letter.c lex.l mailz.c
SRCS += parse.y printable.c read-letter.c read-letters.c send.c setup.c
LDADD = -lutil
NOMAN = 1

BINDIR = bin

.include <bsd.prog.mk>
