PROG = maildir-read-letter
SRCS = charset.c content-type.c encoding.c header.c ibuf-util.c
SRCS += imsg-sync.c maildir-read-letter.c string-util.c
NOMAN = 1
LDADD = -lutil

BINDIR = libexec

.include <bsd.prog.mk>
